"""Doc-page-first min_points resolution for Tushare document/2 interface pages.

Design (10 iterations):
  1. Single source of truth: ``document/2?doc_id=*`` page body (live fetch via Playwright).
  2. Persist fetched pages in ``tushare_doc_pages_cache.json`` (api + raw_text + min_points).
  3. Parse access threshold from plain text; ignore frequency-tier points after 「频次」.
  4. Reject fabricated seed text (``sidebar_seed`` template) — never treat as official.
  5. Trust only entries with ``fetcher`` (playwright/httpx) or ``min_points_source=doc_page_live``.
  6. Non-fabricated ``raw_text`` in cache may be parsed offline (``doc_page_parsed``).
  7. Sidebar / bundled JSON supply doc_id + api mapping only — not authoritative min_points.
  8. ``_DOC_ID_OVERRIDES`` fixes wrong sidebar api labels — never hardcodes min_points.
  9. TIA full scan optionally refreshes stale doc_ids before catalog diff (``sync_doc_pages``).
 10. Points audit flags APIs whose bundled hint disagrees with doc page (mismatch report).
"""

from __future__ import annotations

import re

from app.services.tia.scan.tushare_doc_registry import (
    _DEPRECATED_DOC_IDS,
    load_doc_pages_cache,
    parse_access_min_points_from_doc_text,
)

_LIVE_FETCHERS = frozenset({"playwright", "playwright_auth", "httpx", "mock", "mcp_live_compile"})
_TRUSTED_MIN_POINTS_SOURCES = frozenset({"doc_page_live", "doc_page_parsed"})
_STALE_PAGE_SOURCES = frozenset({"sidebar_seed", "sidebar_seed_stub", "doc_id_override", "registry_supplement"})
_UNTRUSTED_PARSE_SOURCES = frozenset({"sidebar_seed", "sidebar_seed_stub", "registry_supplement"})
_FABRICATED_SEED_TEXT = re.compile(
    r"^接口：[a-z][a-z0-9_]*\s*用户需要至少\d+积分才可以调取\s*$",
    re.I,
)


def is_fabricated_seed_text(raw_text: str, *, source: str | None = None) -> bool:
    """Detect placeholder text generated by seed_tushare_doc_pages_cache.py."""
    if not raw_text:
        return False
    if source in _STALE_PAGE_SOURCES:
        return True
    normalized = re.sub(r"\s+", " ", raw_text.strip())
    if len(normalized) > 120:
        return False
    if any(kw in normalized for kw in ("描述", "限量", "频次", "更新时间", "输入参数")):
        return False
    return bool(_FABRICATED_SEED_TEXT.match(normalized))


def is_live_doc_page_entry(entry: dict | None) -> bool:
    """True when cache row came from an actual HTTP/browser fetch."""
    if not entry or entry.get("error"):
        return False
    if entry.get("fetcher") in _LIVE_FETCHERS:
        return True
    return (entry.get("min_points_source") or "") in _TRUSTED_MIN_POINTS_SOURCES


def is_stale_doc_page_entry(entry: dict | None) -> bool:
    """True when cache row must be re-fetched from document/2."""
    if not entry:
        return True
    if entry.get("error"):
        return True
    if is_live_doc_page_entry(entry):
        return False
    if (entry.get("source") or "") in _STALE_PAGE_SOURCES:
        return True
    raw_text = entry.get("raw_text") or ""
    if raw_text and is_fabricated_seed_text(raw_text, source=entry.get("source")):
        return True
    if entry.get("min_points") is not None and not raw_text:
        return True
    return not raw_text


def sanitize_stale_cache_entry(entry: dict) -> dict:
    """Strip fabricated min_points/raw_text from non-live cache rows."""
    cleaned = dict(entry)
    if is_live_doc_page_entry(cleaned):
        return cleaned
    if (cleaned.get("source") or "") in _UNTRUSTED_PARSE_SOURCES or is_fabricated_seed_text(
        cleaned.get("raw_text") or "",
        source=cleaned.get("source"),
    ):
        cleaned.pop("raw_text", None)
        cleaned.pop("min_points", None)
        cleaned.pop("min_points_source", None)
    return cleaned


def parse_min_points_from_cache_entry(entry: dict) -> tuple[int | None, str]:
    """Extract min_points from one cache row (always re-parse raw_text when present)."""
    if entry.get("error"):
        return None, "fetch_error"
    if (entry.get("source") or "") in _UNTRUSTED_PARSE_SOURCES and not is_live_doc_page_entry(entry):
        return None, "stale_seed"
    raw_text = entry.get("raw_text") or ""
    if raw_text and not is_fabricated_seed_text(raw_text, source=entry.get("source")):
        parsed = parse_access_min_points_from_doc_text(raw_text)
        if parsed is not None:
            source = "doc_page_parsed"
            if is_live_doc_page_entry(entry):
                source = str(entry.get("min_points_source") or "doc_page_live")
            return parsed, source
    if is_live_doc_page_entry(entry) and entry.get("min_points") is not None:
        return int(entry["min_points"]), str(entry.get("min_points_source") or "doc_page_live")
    return None, "unknown"


def resolve_min_points_from_doc_page(
    doc_id: int,
    *,
    page_cache: dict[str, dict] | None = None,
) -> tuple[int | None, str]:
    """Resolve min_points for doc_id using only document/2 page cache content."""
    if doc_id in _DEPRECATED_DOC_IDS:
        return None, "deprecated"
    cache = page_cache if page_cache is not None else load_doc_pages_cache()
    entry = cache.get(str(doc_id), {})
    if not entry:
        return None, "unknown"
    return parse_min_points_from_cache_entry(entry)


def list_doc_ids_needing_live_fetch(
    doc_ids: list[int],
    *,
    page_cache: dict[str, dict] | None = None,
) -> list[int]:
    """Doc ids that lack a trusted live document/2 page in cache."""
    cache = page_cache if page_cache is not None else load_doc_pages_cache()
    stale: list[int] = []
    for doc_id in doc_ids:
        if doc_id in _DEPRECATED_DOC_IDS:
            continue
        entry = cache.get(str(doc_id))
        if is_stale_doc_page_entry(entry):
            stale.append(doc_id)
    return sorted(stale)


def resolve_doc_ids_for_scope(
    scope: str,
    *,
    doc_ids: list[int] | None = None,
    sidebar_entries: list[dict] | None = None,
) -> list[int]:
    """Resolve doc_id list for doc-pages sync (snapshot menu links only)."""
    if doc_ids:
        return sorted({int(d) for d in doc_ids if int(d) not in _DEPRECATED_DOC_IDS})

    from app.services.tia.scan.document2_index_builder import load_sidebar_links_from_snapshot

    links, _ = load_sidebar_links_from_snapshot()
    if not links:
        from app.services.tia.scan.tushare_doc_catalog import load_document2_sidebar_raw

        entries = sidebar_entries if sidebar_entries is not None else load_document2_sidebar_raw().get(
            "entries", []
        )
    else:
        entries = links if sidebar_entries is None else sidebar_entries
        if sidebar_entries is None and scope == "resolved":
            page_cache = load_doc_pages_cache()
            from app.services.tia.scan.tushare_doc_registry import load_api_by_doc_id, resolve_sidebar_entry

            api_by_doc = load_api_by_doc_id()
            entries = [
                e
                for e in entries
                if resolve_sidebar_entry(e, api_by_doc=api_by_doc, page_cache=page_cache).get("resolved")
            ]

    return sorted(
        {
            int(e["doc_id"])
            for e in entries
            if e.get("doc_id") is not None and int(e["doc_id"]) not in _DEPRECATED_DOC_IDS
        }
    )


def audit_bundled_vs_doc_page(
    doc_id: int,
    bundled_min_points: int | None,
    *,
    page_cache: dict[str, dict] | None = None,
) -> dict | None:
    """Return mismatch row when bundled hint differs from doc page."""
    doc_pts, source = resolve_min_points_from_doc_page(doc_id, page_cache=page_cache)
    if doc_pts is None or bundled_min_points is None:
        return None
    if int(doc_pts) == int(bundled_min_points):
        return None
    return {
        "doc_id": doc_id,
        "bundled_min_points": int(bundled_min_points),
        "doc_min_points": int(doc_pts),
        "min_points_source": source,
    }


def apply_doc_first_min_points(
    doc_id: int,
    *,
    page_cache: dict[str, dict] | None = None,
    sidebar_min_points: int | None = None,
    bundled_min_points: int | None = None,
) -> tuple[int | None, str]:
    """Full resolution chain: doc page → unknown (bundled kept for audit only)."""
    doc_pts, source = resolve_min_points_from_doc_page(doc_id, page_cache=page_cache)
    if doc_pts is not None:
        return doc_pts, source
    if sidebar_min_points is not None and (page_cache or load_doc_pages_cache()).get(str(doc_id)):
        return None, "stale_doc_page"
    _ = bundled_min_points  # reserved for audit_bundled_vs_doc_page
    return None, "unknown"
